version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      PORT : 3000
      MYSQL_HOST : db
      MYSQL_PORT : 3306
      MYSQL_USERNAME : user_dmic
      MYSQL_PASSWORD : root
      MYSQL_DATABASE : pruebita_nest
      MYSQL_SSL : false
      JWT_SECRET : produccion
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pruebita_nest
      MYSQL_USER: user_dmic
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"